spring:
  application:
    name: Project 1 Email

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: set username here
    password: set password here
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

server:
  port: 8081
