spring:
  application:
    name: Project 1
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    username: postgres
    password: Elessar1989!
    url: jdbc:postgresql://34.69.191.73:5432/project1_jaab
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  
